### ISSUE TITLE
hugoとかOctpressとかなんかMarkdownで書けるCMSを導入する

### ISSUE THREAD

**Issue by nabeen** [Catatsu/catatsu#1]

**Comment by matumotto** [comment]
わぁい

**Comment by nabeen** [comment]
@matumotto 
Werker用のymlはこんな感じでいけるぽよ

wercker.yml
```yml
box: debian
build:
  steps:
    - arjen/hugo-build@1.8.1:
      flags: --buildDrafts=false
      theme: hugo-icarus
deploy:
  steps:
    - install-packages:
        packages: git ssh-client
    - lukevivier/gh-pages@0.2.1:
        token: $GIT_TOKEN
        basedir: public
        repo: foo/bar
```
